name: Lint Code Base

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        id: eslint
        run: npm run lint

      - name: Output ESLint Result
        if: failure()
        run: cat eslint-output.txt

      - name: Comment on Pull Request
        if: failure()
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const github = require('@actions/github');
            const lintOutput = fs.readFileSync('eslint-output.txt', 'utf8');
            const issue_number = github.context.payload.pull_request.number;

            await github.getOctokit(process.env.GITHUB_TOKEN).rest.issues.createComment({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              issue_number,
              body: `:warning: Linting issues found:\n\n\`\`\`text\n${lintOutput}\n\`\`\``
            });
