name: Lint Code Base

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: |
          npx eslint . --ext .js,.jsx,.ts,.tsx -f json -o eslint-report.json || true

      - name: Install Reviewdog
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Reviewdog
        run: |
          reviewdog -f=eslint -name="eslint" -reporter=github-pr-review -level=error -fail-on-error < eslint-report.json
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
