name: Lint Code Base

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  eslint:
    name: Run ESLint and comment results
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: |
          npx eslint . --ext .js,.jsx,.ts,.tsx -f unix > eslint-report.txt || true

      - name: Upload ESLint Report
        uses: actions/upload-artifact@v2
        with:
          name: eslint-report
          path: eslint-report.txt

  reviewdog:
    name: Reviewdog Comment
    runs-on: ubuntu-latest
    needs: eslint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download ESLint Report
        uses: actions/download-artifact@v2
        with:
          name: eslint-report

      - name: Run Reviewdog
        run: |
          cat eslint-report.txt | reviewdog -f=eslint -name="eslint" -reporter=github-pr-review -level=error -fail-on-error -filter-mode=added
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
