name: Lint Code Base

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  eslint:
    name: Run ESLint and comment results
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: |
          npx eslint . --ext .js,.jsx,.ts,.tsx -f json -o eslint-report.json || true

      - name: Reviewdog GitHub Action
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          filter_mode: added
          fail_on_error: true
          reviewdog_flags: "-f=json -reporter=github-pr-review -fail-on-error -level=error"
          tool_name: eslint
