name: Lint Code Base

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # ... outras etapas ...

      - name: Comment on Pull Request
        if: failure()
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { getOctokit } = require('@actions/github');
            const { owner, repo, payload: { pull_request: { number: issue_number }}} = context;
            const lintOutput = fs.readFileSync('eslint-output.txt', 'utf8');

            const octokit = getOctokit(process.env.GITHUB_TOKEN);

            await octokit.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: `:warning: Linting issues found:\n\n\`\`\`text\n${lintOutput}\n\`\`\``
            });
